package com.iot.plugin.sdkdev.database.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.SelectProvider;

import com.iot.plugin.sdkdev.database.model.TransData;

public interface DataDao {
    @Insert({
        "insert into ${tableName} (id,",
        "point_id, ",
        "point_name, ",
        "device_id, ",
        "device_name, ",
        "region_code, ",
        "region_name, " ,
        "sourcepoint_id, " ,
        "monitor_time, " ,
        "create_time, " ,
        "time_key, " ,
        "first_pollutant, " ,
        "level, " ,
        "aqi, " ,
        "so2, " ,
        "co, " ,
        "no, " ,
        "no2, " ,
        "pm25, " ,
        "pm2524, " ,
        "pm10, " ,
        "pm1024, " ,
        "o3, " ,
        "o38, " ,
        "tsp, " ,
        "noise, " ,
        "vocs, " ,
        "tvocs, " ,
        "nh3, " ,
        "gas, " ,
        "coc12, " ,
        "ch4s, " ,
        "h2s, " ,
        "cl2, " ,
        "secaline, " ,
        "c2h6s, " ,
        "c2h6s2, " ,
        "cs2, " ,
        "c8h8, " ,
        "wd, " ,
        "ws, " ,
        "tem, " ,
        "pa, " ,
        "rh, " ,
        "v1, " ,
        "v2, " ,
        "v3, " ,
        "v4, " ,
        "v5)",
        "values (#{id,jdbcType=VARCHAR}, ",
        "#{point_id,jdbcType=VARCHAR},",
        "#{point_name,jdbcType=VARCHAR},",
        "#{device_id,jdbcType=VARCHAR},",
        "#{device_name,jdbcType=VARCHAR},",
        "#{region_code,jdbcType=VARCHAR},",
        "#{region_name,jdbcType=VARCHAR},",
        "#{sourcepoint_id,jdbcType=VARCHAR},",
        "#{monitor_time,jdbcType=TIMESTAMP},",
        "#{create_time,jdbcType=TIMESTAMP},",
        "#{time_key,jdbcType=VARCHAR},",
        "#{first_pollutant,jdbcType=VARCHAR},",
        "#{level,jdbcType=VARCHAR},",
        "#{aqi,jdbcType=DOUBLE },",
        "#{so2,jdbcType=DOUBLE },",
        "#{co,jdbcType=DOUBLE },",
        "#{no,jdbcType=DOUBLE },",
        "#{no2,jdbcType=DOUBLE }, ",
        "#{pm25,jdbcType=DOUBLE }, ",
        "#{pm2524,jdbcType=DOUBLE }, ",
        "#{pm10,jdbcType=DOUBLE }, ",
        "#{pm1024,jdbcType=DOUBLE }, ",
        "#{o3,jdbcType=DOUBLE }, ",
        "#{o38,jdbcType=DOUBLE }, ",
        "#{tsp,jdbcType=DOUBLE }, ",
        "#{noise,jdbcType=DOUBLE }, ",
        "#{vocs,jdbcType=DOUBLE }, ",
        "#{tvocs,jdbcType=DOUBLE }, ",
        "#{nh3,jdbcType=DOUBLE }, ",
        "#{gas,jdbcType=DOUBLE }, ",
        "#{coc12,jdbcType=DOUBLE }, ",
        "#{ch4s,jdbcType=DOUBLE }, ",
        "#{h2s,jdbcType=DOUBLE }, ",
        "#{cl2,jdbcType=DOUBLE }, ",
        "#{secaline,jdbcType=DOUBLE }, ",
        "#{c2h6s,jdbcType=DOUBLE }, ",
        "#{c2h6s2,jdbcType=DOUBLE }, ",
        "#{cs2,jdbcType=DOUBLE }, ",
        "#{c8h8,jdbcType=DOUBLE }, ",
        "#{wd,jdbcType=DOUBLE },",
        "#{ws,jdbcType=DOUBLE },",
        "#{tem,jdbcType=DOUBLE },",
        "#{pa,jdbcType=DOUBLE },",
        "#{rh,jdbcType=DOUBLE },",
        "#{v1,jdbcType=DOUBLE },",
        "#{v2,jdbcType=DOUBLE },",
        "#{v3,jdbcType=DOUBLE },",
        "#{v4,jdbcType=DOUBLE },",
        "#{v5,jdbcType=DOUBLE })"
    })
    Integer insert(TransData transData);
    
	@SelectProvider(type=DataSqlProvider.class, method="getTableData")
    List<Map<String, Object>> getTableData(Map<String, String> map);
}
